AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS PostgreSQL para API Festivos - Configuración Free Tier (Costo Cero)'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Ambiente de deployment

  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    Description: Password para usuario admin de la base de datos
    ConstraintDescription: Debe tener entre 8 y 41 caracteres

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID donde crear los recursos

  PrivateSubnetIds:
    Type: CommaDelimitedList
    Description: Lista de subnet IDs privadas (al menos 2 para RDS)

Resources:
  # Security Group para RDS - Free Tier (sin dependencias circulares)
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group para RDS PostgreSQL - Free Tier
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
          Description: Acceso PostgreSQL desde cualquier IP (solo para desarrollo)
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-festivos-db-sg'
        - Key: Environment
          Value: !Ref Environment
        - Key: CostOptimization
          Value: FreeTier

  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group para RDS PostgreSQL
      SubnetIds: !Ref PrivateSubnetIds
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-festivos-db-subnet-group'
        - Key: Environment
          Value: !Ref Environment

  # RDS PostgreSQL Instance - FREE TIER OPTIMIZED
  FestivosDatabase:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete  # Para free tier, no mantener snapshots
    Properties:
      DBInstanceIdentifier: !Sub '${Environment}-festivos-postgres'
      DBInstanceClass: db.t3.micro  # FREE TIER: 750 horas/mes gratis
      Engine: postgres
      EngineVersion: '15.13'  # Versión disponible más reciente
      MasterUsername: festivos_user
      MasterUserPassword: !Ref DBPassword

      # STORAGE - FREE TIER: 20GB gratis
      AllocatedStorage: 20
      MaxAllocatedStorage: 20  # No permitir auto-scaling para evitar costos
      StorageType: gp2
      StorageEncrypted: false  # Encriptación NO incluida en free tier

      # NETWORKING
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: true  # Cambiar a true para permitir acceso desde ECS
      Port: 5432

      # BACKUP - FREE TIER: Sin backups para evitar costos
      BackupRetentionPeriod: 0  # Sin backups automáticos (evita costos)
      DeleteAutomatedBackups: true

      # MAINTENANCE
      PreferredMaintenanceWindow: 'sun:03:00-sun:04:00'
      AutoMinorVersionUpgrade: true
      DeletionProtection: false  # Permitir eliminación fácil

      # MONITORING - FREE TIER: Sin monitoring avanzado
      MonitoringInterval: 0  # Sin Enhanced Monitoring (evita costos)
      EnablePerformanceInsights: false  # Sin Performance Insights
      EnableCloudwatchLogsExports: []  # Sin logs a CloudWatch

      # MISC
      MultiAZ: false  # Sin Multi-AZ (evita costos)
      CopyTagsToSnapshot: false

      Tags:
        - Key: Name
          Value: !Sub '${Environment}-festivos-postgres'
        - Key: Environment
          Value: !Ref Environment
        - Key: CostOptimization
          Value: FreeTier
        - Key: BackupStrategy
          Value: None

Outputs:
  DBEndpoint:
    Description: RDS PostgreSQL Endpoint
    Value: !GetAtt FestivosDatabase.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-DBEndpoint'

  DBPort:
    Description: RDS PostgreSQL Port
    Value: !GetAtt FestivosDatabase.Endpoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-DBPort'

  DatabaseURL:
    Description: JDBC URL completa para la aplicación
    Value: !Sub 'jdbc:postgresql://${FestivosDatabase.Endpoint.Address}:${FestivosDatabase.Endpoint.Port}/festivos'
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseURL'

  DBSecurityGroupId:
    Description: Security Group ID para base de datos
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-DBSecurityGroup'

  FreeTierOptimizations:
    Description: Optimizaciones aplicadas para Free Tier
    Value: 'db.t3.micro, 20GB storage, no backups, no monitoring, no encryption, no Multi-AZ'
